/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as DecksDeckIdChecklistRouteImport } from './routes/decks.$deckId_.checklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksRoute,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRoute,
} as any)
const DecksDeckIdChecklistRoute = DecksDeckIdChecklistRouteImport.update({
  id: '/$deckId_/checklist',
  path: '/$deckId/checklist',
  getParentRoute: () => DecksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
  '/decks/$deckId/checklist': typeof DecksDeckIdChecklistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks': typeof DecksIndexRoute
  '/decks/$deckId/checklist': typeof DecksDeckIdChecklistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
  '/decks/$deckId_/checklist': typeof DecksDeckIdChecklistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks'
    | '/health'
    | '/history'
    | '/search'
    | '/shared'
    | '/stats'
    | '/decks/$deckId'
    | '/decks/'
    | '/decks/$deckId/checklist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/history'
    | '/search'
    | '/shared'
    | '/stats'
    | '/decks/$deckId'
    | '/decks'
    | '/decks/$deckId/checklist'
  id:
    | '__root__'
    | '/'
    | '/decks'
    | '/health'
    | '/history'
    | '/search'
    | '/shared'
    | '/stats'
    | '/decks/$deckId'
    | '/decks/'
    | '/decks/$deckId_/checklist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRoute: typeof DecksRouteWithChildren
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  SharedRoute: typeof SharedRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof DecksRoute
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/decks/$deckId_/checklist': {
      id: '/decks/$deckId_/checklist'
      path: '/$deckId/checklist'
      fullPath: '/decks/$deckId/checklist'
      preLoaderRoute: typeof DecksDeckIdChecklistRouteImport
      parentRoute: typeof DecksRoute
    }
  }
}

interface DecksRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
  DecksDeckIdChecklistRoute: typeof DecksDeckIdChecklistRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksIndexRoute: DecksIndexRoute,
  DecksDeckIdChecklistRoute: DecksDeckIdChecklistRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRoute: DecksRouteWithChildren,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  SharedRoute: SharedRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
