/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksRoute,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => DecksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks': typeof DecksRouteWithChildren
  '/history': typeof HistoryRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks'
    | '/history'
    | '/search'
    | '/shared'
    | '/decks/$deckId'
    | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/search' | '/shared' | '/decks/$deckId' | '/decks'
  id:
    | '__root__'
    | '/'
    | '/decks'
    | '/history'
    | '/search'
    | '/shared'
    | '/decks/$deckId'
    | '/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksRoute: typeof DecksRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  SearchRoute: typeof SearchRoute
  SharedRoute: typeof SharedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof DecksRoute
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof DecksRoute
    }
  }
}

interface DecksRouteChildren {
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksIndexRoute: DecksIndexRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksRoute: DecksRouteWithChildren,
  HistoryRoute: HistoryRoute,
  SearchRoute: SearchRoute,
  SharedRoute: SharedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
